### ISSUE TITLE
JsonFeeder needs to copy bytes, even if source already is ByteBuffer

### ISSUE THREAD

**Issue by jypma** [michel-kraemer/actson#1]
Currently `JsonFeeder` lacks the ability to directly feed off read-only `ByteBuffer` objects. This has the disadvantage of needing another copy operation for frameworks that offer input bytes as `ByteBuffer` (e.g. akka's `ByteString` and google protobuf's `ByteString` do this).

`JsonFeeder` should be extended to read from byte buffers as well. On the implementation side, I see two possible implementations:
1. Hold on to the byte buffers if they're read-only, and process them once `fillBuffer` is called (no copying)
2. Immediately read them into characters when feeding, holding on to only a few final bytes if we happen to land in the middle of a multi-byte sequence.

Actually, glancing at the code, is (2) even handled currently?

I'd be happy to do a PR.

**Comment by michel-kraemer** [comment]
Thank you very much for your excellent ideas!

I already thought about the same thing(s). However, I would recommend extending `DefaultJsonFeeder` instead of changing the interface `JsonFeeder`. Is that what you meant?

Regarding (2): the feeder can handle partial characters (i.e. if we land in the middle of a multi-byte sequence), but it doesn't take the short cut to copy bytes directly to the CharBuffer if they're ASCII. This is an optimisation worth implementing.

I really like your ideas. I could implement them some time in the future, but I don't know exactly when I have time for them. If you like you can send me a pull request. This would be very much appreciated.

Cheers,
Michel

**Comment by michel-kraemer** [comment]
Hi!

I was playing around with this a bit. I created a quick benchmark that measures the performance of the `DefaultJsonFeeder` and a simple implementation that does not need to copy bytes:

https://gist.github.com/michel-kraemer/910b68862d2d01bd8fd0c6e4f03705bf

It's very hard to get reasonable results here. It all depends very much on the use case. If you execute the benchmark as it is, you'll see that the `FastFeeder` performs actually worse than the `DefaultJsonFeeder`. This is due to the fact that it only operates on one buffer at a time and the JSON chunks that I feed into it are too small. If I make them larger the performance gets better but not very much. It seems to me it's not really worth the effort and the JSON file has to be rather large for the `FastFeeder` to perform better than the default one. So - as I said - it really depends on the use case.

You may use the Gist to perform your own tests. I'm looking forward to your results.

Michel

**Comment by michel-kraemer** [comment]
Or maybe my implementation of `FastFeeder` is just too bad. Please let me know if you find a better one.

**Comment by jypma** [comment]
My original suggestion was actually to extend the interface to accept `ByteBuffer` directly, so that the path needn't be `ByteBuffer` -> `byte[]` -> `char[]`, but rather can go from byte buffer into chars directly. 

However, I actually came across a similar case last week, where i needed to copy to `byte[]` from another structure in order to integrate a base 64 decoder. I was doing proper profiling, and actually it turned out that copying the bytes didn't even show up as a noticeable bottleneck. In other words, actually doing the parsing in many cases takes much more time compared to copying chunks of bytes (which can be done rather performantly). This means I'm actually fine with the way actson currently is, and don't expect any bottleneck from the copying part.

I think that may also be what your benchmark is showing. You may want to put your code into one of the microharnass benchmark frameworks though, since often hotspot will go and tweak things for the better after a few 1000 iterations or more.

**Comment by michel-kraemer** [comment]
Thanks for the feedback. So, I'm going to close this issue now. If you need anything else, please feel free to open it again or create a new issue.

Cheers,
Michel

**Comment by jypma** [comment]
Thanks a lot for looking into it!

By the way, we're using Actson in our parser combinator-based non-blocking marshalling library, see [here](https://github.com/Tradeshift/ts-reaktive/tree/master/ts-reaktive-marshal), in case you're interested :-)

**Comment by jypma** [comment]
@michel-kraemer Completely unrelated, but it might be fun to pull actson through the JSON parser corner cases mentioned [here](http://seriot.ch/parsing_json.html), to see what happens :-)

**Comment by michel-kraemer** [comment]
Cool. Thanks for the link. It will most likely suffer from the issues described in section 4.8. I will test that.

**Comment by michel-kraemer** [comment]
I created an issue for it: #2
