### ISSUE TITLE
performance review?

### ISSUE THREAD

**Issue by Ziemien** [michel-kraemer/actson#7]
Hi 

How does the performance compare with existing libraries such as Jackson? I consider using it for network application in which JSON messages arrive in chunks.

**Comment by michel-kraemer** [comment]
This is a very good question! You cannot really compare Actson and Jackson, because they have completely different architectures. Personally, I love Jackson very much and use it whenever I can because it's extremely fast and easy to use. Tatu has put a lot of work in optimizing Jackson and making it one of the fastest and versatile JSON parsers available.

Actson on the other hand is also extremely fast. The parser code is very small and doesn't leave much room for optimisation. I think, it's on par with Jackson. I can't present numbers, but I did a bit of benchmarking a while ago and it looked really good. Feature-wise it's not as comprehensive as Jackson, not least because it does not support generating JSON.

It all depends on your use case. If you need something that is easy to use and reliable, go for Jackson. However, if you need an asynchronous non-blocking parser then you should use Actson. In practise you won't see much difference between the two performance-wise. But if your application already is non-blocking (e.g. if you're using Vert.x or something similar) then you might actually get a better performance with Actson overall (at least in terms of scalability probably).

Let me know if this helps! Please close the issue if you don't have any further questions. Thanks!

**Comment by htmldoug** [comment]
Jackson just added an async parser in https://github.com/FasterXML/jackson-core/issues/57 and published a pre-release
 ([jackson-core-2.9.0.pr4](https://github.com/FasterXML/jackson-core/releases/tag/jackson-core-2.9.0.pr4)).

I've put together [two benchmarks](https://github.com/htmldoug/json-async-benchmarks):
1. `bookstoreAllBytesAtOnce` parses bookstore.json and makes the bytes available immediately
2. `oneHundredBookStoresStreamed` parses an array of 100x bookstore.json one bookstore byte[] at a time.

```
> bench/jmh:run -wi 15 -i 30 -f3 -t1 .*
[info] Benchmark                                    (implementation)   Mode  Cnt       Score      Error  Units
[info] JsonBenchmarks.bookstoreAllBytesAtOnce                 actson  thrpt   90   91527.435 ± 1423.217  ops/s
[info] JsonBenchmarks.bookstoreAllBytesAtOnce                jackson  thrpt   90  228358.584 ± 3672.275  ops/s
[info] JsonBenchmarks.oneHundredBookStoresStreamed            actson  thrpt   90    1018.986 ±   22.096  ops/s
[info] JsonBenchmarks.oneHundredBookStoresStreamed           jackson  thrpt   90    3335.238 ±   60.136  ops/s
```

Jackson's `NonBlockingJsonParser` appears to be 2x-3x faster than actson over these tests.
